### ISSUE TITLE
Problem with display_cover_image, OSError

### ISSUE THREAD

**Issue by pazu1** [alnj/ncmpcpp-ueberzug#8]
Album art is not displayed and the function `display_cover_image` in file _ncmpcpp_cover_art.sh_ outputs the following error.

```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "<stdin>", line 5, in get_geometry
OSError: [Errno 25] Inappropriate ioctl for device
awk: fatal: cannot open file `/tmp/ncmpcpp_geometry.txt' for reading: No such file or directory
awk: fatal: cannot open file `/tmp/ncmpcpp_geometry.txt' for reading: No such file or directory
rm: cannot remove '/tmp/ncmpcpp_geometry.txt': No such file or directory
/home/user/.config/ncmpcpp/ncmpcpp_cover_art.sh: line 114: ueber_height * font_height / font_width : division by 0 (error token is "font_width ")
```

The program worked fine before but after doing some updates this issue appeared. Any idea what might've caused this?

**Comment by pazu1** [comment]
I got it working by using xwininfo to calculate dimensions instead of python
In case somebody else has this problem, just replace _guess_terminal_pixelsize_ function with this
```
guess_terminal_pixelsize() {

    gwidth=$(printf "$(xwininfo -id $WINDOWID)" | grep Width)
    term_width=$(echo $gwidth | awk '{print $2}')
    gheight=$(printf "$(xwininfo -id $WINDOWID)" | grep Height)
    term_height=$(echo $gheight | awk '{print $2}')

    if ! is_font_size_successfully_computed; then
        echo "Failed to guess font size, try setting it in ncmpcpp_cover_art.sh settings"
    fi
}

```

**Comment by alnj** [comment]
Thank you for sharing your solution. I haven't had the time to look into that issue...

I believe xwininfo is something I tried but it had smaller support across terminals (at the time).

**Comment by alnj** [comment]
By the way: what distro are you using?

**Comment by pazu1** [comment]
Arch
